Add check for working ffcall
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/tools/startup/trunk@24861 72102866-910b-0410-8b05-ffd578937521

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2868,7 +2868,7 @@ cc_apple=no
 if test  $cc_result = 0; then
   case $host_os in
      darwin*)
-       SETUP_ERRORS="$SETUP_ERRORS W093"
+       SETUP_ERRORS="$SETUP_ERRORS E093"
        cc_apple=yes;;
   esac
 fi
@@ -3239,13 +3239,8 @@ echo "${ECHO_T}no" >&6
 fi
 
 
-GNU_MAKE=make
-case $host_os in
-     *bsd* | *BSD*)
-       GNU_MAKE=gmake;;
-esac
-# Extract the first word of "$GNU_MAKE", so it can be a program name with args.
-set dummy $GNU_MAKE; ac_word=$2
+# Extract the first word of "gmake", so it can be a program name with args.
+set dummy gmake; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_GNUMAKE+set}" = set; then
@@ -3261,7 +3256,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_GNUMAKE=""
+    ac_cv_prog_GNUMAKE="make"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -3281,7 +3276,7 @@ fi
 
 echo "$as_me:$LINENO: checking make version > 3.75" >&5
 echo $ECHO_N "checking make version > 3.75... $ECHO_C" >&6
-make_version=`$GNU_MAKE --version | grep "[0-9]\.[0-9][0-9]" | sed "s/\(^[^0-9]*\)\([0-9]\.[0-9][0-9]*\)\([^0-9].*\)/\2/"`
+make_version=`$GNUMAKE --version | grep "[0-9]\.[0-9][0-9]" | sed "s/\(^[^0-9]*\)\([0-9]\.[0-9][0-9]*\)\([^0-9].*\)/\2/"`
 if test -n "$make_version" -a "$make_version" \> 3.74; then
   echo "$as_me:$LINENO: result: yes $make_version" >&5
 echo "${ECHO_T}yes $make_version" >&6
@@ -7210,6 +7205,41 @@ echo "${ECHO_T}ffcall" >&6
   else
     LIBS="$saved_LIBS"
   fi
+  echo "$as_me:$LINENO: checking if ffcall trampolines work" >&5
+echo $ECHO_N "checking if ffcall trampolines work... $ECHO_C" >&6
+  if test "$cross_compiling" = yes; then
+  have_working_trampoline=yes
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#include "$srcdir/config/config.trampoline.c"
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  have_working_trampoline=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+have_working_trampoline=no
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+  echo "$as_me:$LINENO: result: $have_working_trampoline" >&5
+echo "${ECHO_T}$have_working_trampoline" >&6
+  if test $have_working_trampoline = no; then
+    ffi_ok=no
+  fi
 else
   ffi_ok=no
 fi
@@ -7220,6 +7250,8 @@ echo "${ECHO_T}none" >&6
   if test $have_forward_hook = no; then
     # Need the warning for MingW when libobjc is moved out of the way
     SETUP_ERRORS="$SETUP_ERRORS W272"
+  elif test "$have_working_trampoline" = no; then
+    SETUP_ERRORS="$SETUP_ERRORS E273"
   else
     SETUP_ERRORS="$SETUP_ERRORS W270"
   fi
