* Version 0.9.1 * InstallGNUstep: Add logging output to file. Check for previous versions and allow upgrading (or not). A little better documentation. * configure.ac: Remove some unneeded checks. Check currently installed versions.
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/tools/startup/trunk@20753 72102866-910b-0410-8b05-ffd578937521

diff --git a/InstallGNUstep b/InstallGNUstep
--- a/InstallGNUstep
+++ b/InstallGNUstep
@@ -1,7 +1,35 @@
 #!/bin/sh
+#
+#  Copyright (C) 2005 Free Software Foundation, Inc.
+#
+#  Written by:	Adam Fedor <fedor@gnu.org>
+#
+#  This package is free software; you can redistribute it and/or
+#  modify it under the terms of the GNU General Public License as
+#  published by the Free Software Foundation; either version 2 of the
+#  License, or (at your option) any later version.
+#
+#  This package is distributed in the hope that it will be useful,
+#  but WITHOUT ANY WARRANTY; without even the implied warranty of
+#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	 See the GNU
+#  General Public License for more details.
+#
+#  You should have received a copy of the GNU General Public
+#  License along with this package; if not, write to the Free
+#  Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111 USA
+#
+#--------------------------------------------------------------------
+#
+# This is a simple script used to setup and compile the GNUstep core
+# packages. It runs a configure script to check the system and then
+# compiles and installs the packages if all the prerequisites are 
+# satisfied. To run this script, at the command line, type
+#
+# InstallGNUstep
 
 #--------------------------------------------------------------------
-# Check the shell
+# Check the shell. Do a few checks on how the shell behaves, so that we
+# can run and display things properly.
 #--------------------------------------------------------------------
 case `echo "testing\c"; echo 1,2,3`,`echo -n testing; echo 1,2,3` in
   *c*,-n*) ECHO_N= ECHO_C='
@@ -12,7 +40,8 @@ esac
 
 
 #--------------------------------------------------------------------
-# Misc setup
+# Misc setup. Set the default source, build, and install directories.
+# Also source the sub-scripts that contain functions that we need.
 #--------------------------------------------------------------------
 
 SRCDIR=`pwd`
@@ -36,7 +65,9 @@ fi
 
 gs_platform
 
-LIB_COMBO=gnu-gnu-gnu
+if test -z "$LIBRARY_COMBO"; then
+  LIBRARY_COMBO=gnu-gnu-gnu
+fi
 
 if [ -z "$MAKE" ]; then
   if gmake -v >/dev/null 2>&1
@@ -68,7 +99,9 @@ echo
 echo
 
 #--------------------------------------------------------------------
-# Check how we can install (as root, sudo, home dir, etc)
+# Check how we can install. If we are running as root, just go
+# ahead. Otherwise ask the user if they can install via sudo or if
+# they just want to try it in their home directory.
 #--------------------------------------------------------------------
 HAVE_SUDO=no
 NO_PRIV=no
@@ -130,21 +163,29 @@ if [ $AS_ROOT = no -a $HAVE_SUDO = yes ]; then
 fi
 
 #--------------------------------------------------------------------
-# Find GNUstep sources
+# Find GNUstep sources. Check first if there is a 'core' directory
+# at the same level as us. If so, we are compiling from CVS sources.
+# Otherwise check in the 'sources' subdirectory for all the packages
+# we need.
 #--------------------------------------------------------------------
-FOUND_FFCALL=yes
-FFCALL=`find $SOURCESDIR -name ffcall-1*`
-if [ x$FFCALL = x ]; then
+if [ -d $SOURCESDIR ]; then
+  FOUND_FFCALL=yes
+  FFCALL=`find $SOURCESDIR -name ffcall-1*`
+  if [ x$FFCALL = x ]; then
+    FOUND_FFCALL=no
+  else
+    FFCALL=`basename $FFCALL .tar.gz`
+  fi
+  FOUND_LIBOBJC=yes
+  LIBOBJC=`find $SOURCESDIR -name gnustep-objc*`
+  if [ x$LIBOBJC = x ]; then
+    FOUND_LIBOBJC=no
+  else
+    LIBOBJC=`basename $LIBOBJC .tar.gz`
+  fi
+else
   FOUND_FFCALL=no
-else
-  FFCALL=`basename $FFCALL .tar.gz`
-fi
-FOUND_LIBOBJC=yes
-LIBOBJC=`find $SOURCESDIR -name gnustep-objc*`
-if [ x$LIBOBJC = x ]; then
   FOUND_LIBOBJC=no
-else
-  LIBOBJC=`basename $LIBOBJC .tar.gz`
 fi
 
 FOUND_SOURCES=yes
@@ -158,6 +199,7 @@ if [ -d $SRCDIR/../core ]; then
   GBASE=base
   GGUI=gui
   GBACK=back
+  echo Compiling packages from CVS
 else
   # Compile from tar.gz
   GMAKE=`find $SOURCESDIR -name gnustep-make*`
@@ -186,25 +228,10 @@ else
   GBACK=`basename $GBACK .tar.gz`
 fi
 
-if [ $FOUND_SOURCES = no ]; then
-  echo "******** Source files not found **********"
-  echo "The sources directory in this package had no source packages"
-  echo "which should have all the proper gnustep tar.gz files"
-  echo "(e.g. gnustep-make-x.x.x.tar.gz)"
-  echo "Contact bug-gnustep@gnu.org for help"
-  exit 1
-fi
-
 #--------------------------------------------------------------------
-# Configure
+# Create the build directory if it does not already
+# exist.
 #--------------------------------------------------------------------
-echo "Configuring for $gs_machine"
-gs_flags
-PKG_CPPFLAGS=CPPFLAGS=$GS_CPPFLAGS
-PKG_LDFLAGS=LDFLAGS=$GS_LDFLAGS
-echo $PKG_CPPFLAGS
-echo $PKG_LDFLAGS
-
 if [ \! -d $BUILDDIR ]; then
   mkdir $BUILDDIR
 fi
@@ -231,10 +258,47 @@ cd $BUILDDIR
 if [ \! -d logs ]; then
   mkdir logs
 fi
+rm -f logs.tar.gz
+exec 5>logs/installgnustep.log
+echo "Install log for the InstallGNUstep script" >&5
+echo "Source files:" >&5
+echo " CVS: $IS_CVS " >&5
+echo $GMAKE >&5
+echo $GBASE >&5
+echo $GGUI >&5
+echo $GBACK >&5
+echo "" >&5
 
+if [ $FOUND_SOURCES = no ]; then
+  echo "******** Source files not found **********"
+  echo "The sources directory in this package had no source packages"
+  echo "which should have all the proper gnustep tar.gz files"
+  echo "(e.g. gnustep-make-x.x.x.tar.gz)"
+  echo "Contact bug-gnustep@gnu.org for help"
+  echo "Source files not found. STOP" >&5
+  exit 1
+fi
+
+#--------------------------------------------------------------------
+# Configure. Run the configure script which checks the system out.
+#--------------------------------------------------------------------
 echo "******** Checking system for installation issues **********"
-$SRCDIR/configure --with-library-combo=$LIB_COMBO $PKG_CPPFLAGS $PKG_LDFLAGS
+echo "Configuring for $gs_machine" >&5
+echo "Configuring for $gs_machine"
+gs_flags
+PKG_CPPFLAGS=CPPFLAGS=$GS_CPPFLAGS
+PKG_LDFLAGS=LDFLAGS=$GS_LDFLAGS
+echo $PKG_CPPFLAGS >&5
+echo $PKG_CPPFLAGS
+echo $PKG_LDFLAGS >&5
+echo $PKG_LDFLAGS
 
+echo "" >&5
+echo "$SRCDIR/configure --with-library-combo=$LIBRARY_COMBO $PKG_CPPFLAGS $PKG_LDFLAGS" >&5
+$SRCDIR/configure --with-library-combo=$LIBRARY_COMBO $PKG_CPPFLAGS $PKG_LDFLAGS
+
+# Now print out a report for the user describing any problems with their
+# system that we found.
 cp config.log logs/00-config.log
 cp $SRCDIR/setuperrors .
 cp $SRCDIR/ErrorList .
@@ -248,28 +312,94 @@ if [ $? != 0 ]; then
   echo "Please email bug-gnustep@gnu.org and send the $BUILDDIR/logs.tar.gz file"
   exit 1
 fi
-. setupvars
 
-echo
+# Read in the current setup. Check the versions of the installed packages 
+# against the ones we have and ask the user if there is a discrepancy.
+. setupvars
+if [ $IS_CVS = yes ]; then
+  CURRENT_MAKE_VERSION=CVS
+  CURRENT_BASE_VERSION=CVS
+  CURRENT_GUI_VERSION=CVS
+else
+  CURRENT_MAKE_VERSION=`echo $GMAKE | sed "s/.*-\([0-9.]\)/\1/"`
+  CURRENT_BASE_VERSION=`echo $GBASE | sed "s/.*-\([0-9.]\)/\1/"`
+  CURRENT_GUI_VERSION=`echo $GGUI | sed "s/.*-\([0-9.]\)/\1/"`
+fi
+do_upgrade_make=no
+do_upgrade_base=no
+do_upgrade_gui=no
+if [ "$GNUSTEP_MAKE_VERSION" != 0 ]; then
+  echo Current GNUstep Make version is $GNUSTEP_MAKE_VERSION
+  if [ $GNUSTEP_MAKE_VERSION != $CURRENT_MAKE_VERSION ]; then
+    do_upgrade_make=yes
+  fi
+fi
+if [ $GNUSTEP_BASE_VERSION != 0 ]; then
+  echo Current GNUstep Base version is $GNUSTEP_BASE_VERSION
+  if [ $GNUSTEP_BASE_VERSION != $CURRENT_BASE_VERSION ]; then
+    do_upgrade_base=yes
+  fi
+fi
+if [ $GNUSTEP_GUI_VERSION != 0 ]; then
+  echo Current GNUstep Gui version is $GNUSTEP_GUI_VERSION
+  if [ $GNUSTEP_GUI_VERSION != $CURRENT_GUI_VERSION ]; then
+    do_upgrade_gui=yes
+  fi
+fi
+echo "This package installs these versions of the GNUstep libraries:"
+echo "  GNUstep Make: $CURRENT_MAKE_VERSION"
+echo "  GNUstep Base: $CURRENT_BASE_VERSION"
+echo "  GNUstep Gui: $CURRENT_GUI_VERSION"
+if [ $do_upgrade_make = yes -o $do_upgrade_base = yes -o $do_upgrade_gui = yes ]; then
+  echo You have some GNUstep packages installed already which are not the
+  echo same version as the ones that we will be installing. Do you want to
+  echo "upgrade your packages? (Say no if you want to keep the packages you"
+  echo "currently have installed)"
+  echo $ECHO_N "Install new versions? (y or n): $ECHO_C"
+  read user_option
+  if [ "$user_option" = n -o  "$user_option" = N -o "$user_option" = no -o "$user_option" = NO -o "$user_option" = No ]; then
+    do_upgrade_make=no
+    do_upgrade_base=no
+    do_upgrade_gui=no
+  fi
+fi
+
+echo "Upgrade options:" >&5
+echo " make $do_upgrade_make" >&5
+echo " base $do_upgrade_base" >&5
+echo " gui  $do_upgrade_gui" >&5
+
+echo "" >&5
+echo ""
+echo Building in $BUILDDIR >&5
 echo Building in $BUILDDIR
 if [ x$GNUSTEP_SYSTEM_ROOT = x ]; then
+  echo "Installing in default location (usually /usr/GNUstep)" >&5
   echo "Installing in default location (usually /usr/GNUstep)"
 else
+  echo Installing in $GNUSTEP_SYSTEM_ROOT >&5
   echo Installing in $GNUSTEP_SYSTEM_ROOT
 fi
-echo Library combo: $LIB_COMBO
-echo
+echo Library combo: $LIBRARY_COMBO >&5
+echo Library combo: $LIBRARY_COMBO
+echo "" >&5
+echo ""
 
 if [ "$FFCALL_INSTALLED" = no -a "$LIBFFI_INSTALLED" = no -a "$FOUND_FFCALL" = no ]; then
   echo "******** Source files not found **********"
   echo "Make sure there is a directory one level above this script directory"
   echo "named sources and that it has ffcall-1.8d.tar.gz present"
   echo "Download this file from ftp://ftp.gnustep.org/pub/gnustep/dev-libs"
+  echo "Source files not found. STOP" >&5
   exit 1
 fi
 
 echo $ECHO_N "Press the Return/Enter key to begin building GNUstep: $ECHO_C"
 read user_enter
+if [ "$user_enter" = q ]; then
+  echo "User Stop " >&5
+  exit 0
+fi
 echo
 
 #--------------------------------------------------------------------
@@ -279,8 +409,9 @@ echo
 PLOG=01-make
 PKG=$GMAKE
 PKG_DISPLAY="GNUstep Make"
-PKG_CONFIG=--with-library-combo=$LIB_COMBO
-if [ $GNUSTEP_INSTALLED = yes ];then
+PKG_CONFIG=--with-library-combo=$LIBRARY_COMBO
+if [ $GNUSTEP_INSTALLED = yes -a $do_upgrade_make = no ];then
+  echo GNUstep Make already installed >&5
   echo GNUstep Make already installed
 else
   gs_build_package
@@ -330,8 +461,10 @@ REBUILD_MAKE=no
 #  FFCALL_INSTALLED=no
 #fi
 if [ $FFCALL_INSTALLED = yes ];then
+  echo ffcall already installed >&5
   echo ffcall already installed
 elif [ $LIBFFI_INSTALLED = yes ];then
+  echo libffi already installed >&5
   echo libffi already installed
 else
   gs_build_package
@@ -345,19 +478,20 @@ PKG_CONFIG=NO
 if [ $GCC_VERSION = 2 ]; then
   # Need to install our own version of libobjc
   if [ $GNUSTEP_CUSTOM_LIBOBJC != "NONE" ]; then
+    echo Custom libobjc already installed >&5
     echo Custom libobjc already installed
   elif [ $FOUND_LIBOBJC = no ]; then
+    echo Warning: Could not find gnustep-objc sources to install >&5
     echo Warning: Could not find gnustep-objc sources to install
   else
   gs_build_package
   REBUILD_MAKE=yes
   fi
-fi
-
-# Need to check if libobjc and ffcall got installed...
-if [ \! -f $GNUSTEP_SYSTEM_ROOT/Library/Headers/objc/Object.h ]; then
-  gs_log_error
-  exit 1
+  # Need to check if libobjc and ffcall got installed...
+  if [ \! -f $GNUSTEP_SYSTEM_ROOT/Library/Headers/objc/Object.h ]; then
+    gs_log_error
+    exit 1
+  fi
 fi
 
 #--------------------------------------------------------------------
@@ -367,8 +501,9 @@ fi
 PLOG=03-make
 PKG=$GMAKE
 PKG_DISPLAY="GNUstep Make"
-PKG_CONFIG=--with-library-combo=$LIB_COMBO
+PKG_CONFIG=--with-library-combo=$LIBRARY_COMBO
 if [ $REBUILD_MAKE = no ];then
+  echo No need to update GNUstep Make >&5
   echo No need to update GNUstep Make
 else
   gs_build_package
@@ -387,13 +522,15 @@ PLOG=04-base
 PKG=$GBASE
 PKG_DISPLAY="GNUstep Base"
 PKG_CONFIG=
-if [ "$GNUSTEP_BASE_INSTALLED" = yes ]; then
+if [ "$GNUSTEP_BASE_INSTALLED" = yes -a $do_upgrade_base = no ]; then
+  echo $PKG_DISPLAY already installed >&5
   echo $PKG_DISPLAY already installed
 else
   gs_build_package
 fi
 
-if [ \! -f $GNUSTEP_SYSTEM_ROOT/Library/Headers/Foundation/NSObject.h ]; then
+HEADER_CHECK=$GNUSTEP_SYSTEM_ROOT/Library/Headers/Foundation/NSObject.h
+if [ \! -f $HEADER_CHECK ]; then
   gs_log_error
   exit 1
 fi
@@ -406,13 +543,15 @@ PLOG=05-gui
 PKG=$GGUI
 PKG_DISPLAY="GNUstep Gui"
 PKG_CONFIG=
-if [ "$GNUSTEP_GUI_INSTALLED" = yes ]; then
-  echo GNUstep Gui already installed
+if [ "$GNUSTEP_GUI_INSTALLED" = yes -a $do_upgrade_gui = no ]; then
+  echo $PKG_DISPLAY already installed >&5
+  echo $PKG_DISPLAY already installed
 else
   gs_build_package
 fi
 
-if [ \! -f $GNUSTEP_SYSTEM_ROOT/Library/Headers/AppKit/NSApplication.h ]; then
+HEADER_CHECK=$GNUSTEP_SYSTEM_ROOT/Library/Headers/AppKit/NSApplication.h
+if [ \! -f $HEADER_CHECK ]; then
   gs_log_error
   exit 1
 fi
@@ -425,13 +564,14 @@ PLOG=06-back
 PKG=$GBACK
 PKG_DISPLAY="GNUstep Back"
 PKG_CONFIG=
-if [ "$GNUSTEP_BACK_INSTALLED" = yes ]; then
-  echo GNUstep Back already installed
+if [ "$GNUSTEP_BACK_INSTALLED" = yes  -a $do_upgrade_gui = no ]; then
+  echo $PKG_DISPLAY already installed >&5
+  echo $PKG_DISPLAY already installed
 else
   gs_build_package
 fi
 
-if [ \! -f $GNUSTEP_SYSTEM_ROOT/Library/Bundles/libgnustep-back.bundle/libgnustep-back ]; then
+if [ \! -d $GNUSTEP_SYSTEM_ROOT/Library/Bundles/libgnustep-back.bundle ]; then
   gs_log_error
   exit 1
 fi
@@ -440,7 +580,8 @@ fi
 # Finish 
 #--------------------------------------------------------------------
 
-
+echo "" >&5
+echo "Instalation Finished" >&5
 echo "---------------------------------------------------------"
 echo
 echo Installation Finished
